# Generated by Django 2.1.13 on 2021-10-26 06:52

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('request_type', models.CharField(choices=[('mobile', 'MOBILE'), ('family', 'FAMILY')], max_length=255)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('primary', 'PRIMARY'), ('secondary', 'SECONDARY')], max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('our_church', models.TextField(blank=True, max_length=5000, null=True)),
                ('infrastructure', models.TextField(blank=True, max_length=5000, null=True)),
                ('organization', models.TextField(blank=True, max_length=5000, null=True)),
                ('church_place', models.CharField(max_length=200)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('vicar_inf', models.TextField(blank=True, max_length=50000, null=True)),
                ('vicar_image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('vicar_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'ChurchDetails',
            },
        ),
        migrations.CreateModel(
            name='ChurchFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchVicars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vicar_name', models.CharField(max_length=100)),
                ('vicar_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('vicar_image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('start_year', models.CharField(blank=True, max_length=10, null=True)),
                ('end_year', models.CharField(blank=True, max_length=10, null=True)),
                ('vicar_type', models.CharField(blank=True, choices=[('vicar', 'VICAR'), ('asstvicar', 'ASSTVICAR')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchVikar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vicar_name', models.CharField(max_length=100)),
                ('vicar_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('vicar_image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.ChurchDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='familyimage/')),
                ('members_length', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('primary_user_id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='members/')),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_no_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_no_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('dom', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('marrige_date', models.CharField(blank=True, max_length=20, null=True)),
                ('in_memory', models.BooleanField(default=False)),
                ('in_memory_date', models.DateTimeField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='pan_folder/')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('secondary_user_id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=255)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('dom', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='members/')),
                ('phone_no_secondary_user', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_no_secondary_user_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('marrige_date', models.CharField(blank=True, max_length=20, null=True)),
                ('in_memory', models.BooleanField(default=False)),
                ('in_memory_date', models.DateTimeField(blank=True, null=True)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('primary_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_primary_user', to='church.FileUpload')),
            ],
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_files/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBereavement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Family')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeReadAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeReadPrimary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeReadSecondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('is_json', models.BooleanField(default=False)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_admin', to='api.AdminProfile')),
                ('created_by_primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_primary', to='church.FileUpload')),
                ('created_by_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_secondary', to='church.Members')),
                ('notification_to_admin', models.ManyToManyField(through='church.NoticeReadAdmin', to='api.AdminProfile')),
                ('notification_to_primary', models.ManyToManyField(through='church.NoticeReadPrimary', to='church.FileUpload')),
                ('notification_to_secondary', models.ManyToManyField(through='church.NoticeReadSecondary', to='church.Members')),
            ],
        ),
        migrations.CreateModel(
            name='NumberChangePrimary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from_primary', models.CharField(blank=True, max_length=200, null=True)),
                ('number_from', models.CharField(blank=True, max_length=12, null=True)),
                ('number_to', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('user_type', models.CharField(blank=True, choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('CHURCH', 'CHURCH')], max_length=255, null=True)),
                ('otp', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OtpVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('phone_type', models.CharField(blank=True, choices=[('IOS', 'IOS'), ('ANDROID', 'ANDROID')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('family', models.ManyToManyField(blank=True, null=True, to='church.Family')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Notice')),
                ('primary_user_id', models.ManyToManyField(blank=True, null=True, related_name='get_file_upload_prayergroup', to='church.FileUpload')),
                ('sec_member', models.ManyToManyField(blank=True, null=True, to='church.Members')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryToSecondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from', models.CharField(blank=True, max_length=200, null=True)),
                ('usertype_from', models.CharField(blank=True, max_length=200, null=True)),
                ('request_to', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnapprovedMember',
            fields=[
                ('secondary_user_id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=255)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('dom', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='members/')),
                ('phone_no_secondary_user', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_no_secondary_user_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('marrige_date', models.CharField(blank=True, max_length=20, null=True)),
                ('in_memory', models.BooleanField(default=False)),
                ('in_memory_date', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('edit_user', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.FileUpload')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('address', models.TextField(max_length=500)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_marriage', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_otp_verified', models.BooleanField(default=False)),
                ('is_church_user', models.BooleanField(default=False)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewRequestNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from', models.CharField(blank=True, max_length=200, null=True)),
                ('usertype_from', models.CharField(blank=True, max_length=200, null=True)),
                ('request_to', models.CharField(blank=True, max_length=200, null=True)),
                ('usertype_to', models.CharField(blank=True, max_length=200, null=True)),
                ('request_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='noticereadsecondary',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Notification'),
        ),
        migrations.AddField(
            model_name='noticereadsecondary',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Members'),
        ),
        migrations.AddField(
            model_name='noticereadprimary',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Notification'),
        ),
        migrations.AddField(
            model_name='noticereadprimary',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.FileUpload'),
        ),
        migrations.AddField(
            model_name='noticereadadmin',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Notification'),
        ),
        migrations.AddField(
            model_name='noticereadadmin',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AdminProfile'),
        ),
        migrations.AddField(
            model_name='noticebereavement',
            name='prayer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.PrayerGroup'),
        ),
        migrations.AddField(
            model_name='noticebereavement',
            name='primary_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.FileUpload'),
        ),
        migrations.AddField(
            model_name='noticebereavement',
            name='secondary_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Members'),
        ),
        migrations.AddField(
            model_name='family',
            name='primary_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_file_upload', to='church.FileUpload'),
        ),
        migrations.AddField(
            model_name='churchfolder',
            name='church_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churchfolder', to='church.Images'),
        ),
        migrations.AddField(
            model_name='churchfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.ChurchFolder'),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='image',
            field=models.ManyToManyField(to='church.Images'),
        ),
    ]
