# Generated by Django 2.1.13 on 2019-10-29 06:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='cards/pan_folder/')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'ChurchDetails',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('members_length', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('address', models.TextField(max_length=500)),
                ('occupation', models.CharField(max_length=200)),
                ('about', models.TextField(max_length=5000)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='cards/pan_folder/')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='cards/pan_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='cards/pan_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_register', models.BooleanField(default=False)),
                ('is_user_add_new_member', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OtpModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('user_type', models.CharField(blank=True, choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('CHURCH', 'CHURCH')], max_length=255, null=True)),
                ('otp', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OtpVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Notice')),
                ('user_profile', models.ManyToManyField(to='church.FileUpload')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('address', models.TextField(max_length=500)),
                ('occupation', models.CharField(max_length=200)),
                ('about', models.TextField(max_length=5000)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='cards/pan_folder/')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_marriage', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_otp_verified', models.BooleanField(default=False)),
                ('is_church_user', models.BooleanField(default=False)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Family')),
                ('secondary_user', models.ManyToManyField(to='church.FileUpload')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.UserProfile'),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='image',
            field=models.ManyToManyField(to='church.Images'),
        ),
    ]
