# Generated by Django 2.1.13 on 2021-10-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='family',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='family',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='members',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='members',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='prayergroup',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='prayergroup',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='family',
            name='membership_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
