# Generated by Django 2.1.13 on 2019-11-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdetails',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='vicar_inf',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
