# Generated by Django 2.1.13 on 2019-10-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
