# Generated by Django 2.1.13 on 2021-10-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_auto_20211027_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('group_description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HonourAndRespect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeFarewell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Family')),
                ('prayer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.PrayerGroup')),
            ],
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='address',
            new_name='current_address',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='group_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='parish_name',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='permanent_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'InActive'), ('3', 'Not in Oman'), ('4', 'Ex-Parish Member')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='group_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'InActive'), ('3', 'Not in Oman'), ('4', 'Ex-Parish Member')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='noticefarewell',
            name='primary_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.FileUpload'),
        ),
        migrations.AddField(
            model_name='noticefarewell',
            name='secondary_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Members'),
        ),
        migrations.AddField(
            model_name='group',
            name='primary_user',
            field=models.ManyToManyField(blank=True, null=True, to='church.FileUpload'),
        ),
        migrations.AddField(
            model_name='group',
            name='secondary_user',
            field=models.ManyToManyField(blank=True, null=True, to='church.Members'),
        ),
    ]
