# Generated by Django 2.1.13 on 2019-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_auto_20191101_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
