# Generated by Django 2.1.13 on 2021-11-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_auto_20211029_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='membership_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
