# Generated by Django 2.1.13 on 2019-10-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_churchdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchdetails',
            options={'verbose_name_plural': 'ChurchDetails'},
        ),
    ]
