# Generated by Django 2.1.13 on 2019-11-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20191102_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
