# Generated by Django 2.1.13 on 2021-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20211107_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterField(
            model_name='family',
            name='membership_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
