# Generated by Django 2.1.13 on 2019-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20191023_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.IntegerField(default=0)),
                ('address', models.TextField(max_length=500)),
                ('occupation', models.CharField(max_length=200)),
                ('about', models.TextField(max_length=5000)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='cards/pan_folder/')),
                ('mobile_number', models.IntegerField(default=0)),
            ],
        ),
    ]
