# Generated by Django 2.1.13 on 2019-11-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_auto_20191102_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
    ]
