# Generated by Django 2.1.13 on 2021-11-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_auto_20211107_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='membership_id',
        ),
        migrations.AddField(
            model_name='family',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Membership_id'),
        ),
    ]
