# Generated by Django 2.1.13 on 2019-10-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='family',
        ),
    ]
