# Generated by Django 2.1.13 on 2019-11-03 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_members_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
