# Generated by Django 2.1.13 on 2019-10-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_remove_userprofile_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayergroup',
            old_name='user',
            new_name='user_profile',
        ),
    ]
