# Generated by Django 2.1.13 on 2019-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_auto_20191103_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(default='', upload_to='pan_folder/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
