# Generated by Django 2.1.13 on 2019-11-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_auto_20191103_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
    ]
