# Generated by Django 2.1.13 on 2019-11-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
    ]
