# Generated by Django 2.1.13 on 2019-10-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_auto_20191024_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_marriage',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
