# Generated by Django 2.1.13 on 2019-10-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_auto_20191024_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
