# Generated by Django 2.1.13 on 2019-11-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_fileupload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBereavement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Family')),
                ('prayer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.PrayerGroup')),
                ('primary_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.FileUpload')),
                ('secondary_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Members')),
            ],
        ),
    ]
