# Generated by Django 2.1.13 on 2021-11-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_auto_20211107_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='honourandrespect',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
