# Generated by Django 2.1.13 on 2019-10-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_userprofile_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='cards/pan_folder/')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_marriage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
