# Generated by Django 2.1.13 on 2019-11-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0012_auto_20191105_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='in_memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='members',
            name='in_memory',
            field=models.BooleanField(default=False),
        ),
    ]
