# Generated by Django 2.1.13 on 2019-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_auto_20191024_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=20)),
            ],
        ),
    ]
