# Generated by Django 2.1.13 on 2019-11-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_auto_20191105_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='in_memory_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='in_memory_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
