# Generated by Django 2.1.13 on 2019-10-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_otpmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
