# Generated by Django 2.1.13 on 2019-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_auto_20191105_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
