# Generated by Django 2.1.13 on 2019-11-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0015_family_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='about',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='in_memory',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='in_memory_date',
        ),
        migrations.RemoveField(
            model_name='members',
            name='in_memory',
        ),
        migrations.RemoveField(
            model_name='members',
            name='in_memory_date',
        ),
    ]
