# Generated by Django 2.1.13 on 2019-10-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0015_userprofile_is_otp_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodels',
            old_name='mobile',
            new_name='mobile_number',
        ),
    ]
