# Generated by Django 2.1.13 on 2019-10-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0016_auto_20191024_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=20)),
            ],
        ),
    ]
