# Generated by Django 2.1.13 on 2019-11-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0016_auto_20191105_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='in_memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='in_memory_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='in_memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='members',
            name='in_memory_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
