# Generated by Django 2.1.13 on 2019-10-25 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0017_otpverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodels',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='otpmodels',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
