# Generated by Django 2.1.13 on 2019-11-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0017_auto_20191105_0850'),
        ('church', '0013_churchdetails_vicar_image'),
    ]

    operations = [
    ]
