# Generated by Django 2.1.13 on 2019-10-25 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0018_auto_20191025_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdetails',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='church.Images'),
            preserve_default=False,
        ),
    ]
