# Generated by Django 2.1.13 on 2019-10-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0019_churchdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='date_of_marriage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
