# Generated by Django 2.1.13 on 2019-11-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0019_auto_20191105_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnapprovedMember',
            fields=[
                ('secondary_user_id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('dom', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('phone_no_secondary_user', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_no_secondary_user_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('in_memory', models.BooleanField(default=False)),
                ('in_memory_date', models.CharField(blank=True, max_length=20, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('primary_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.FileUpload')),
            ],
        ),
    ]
