# Generated by Django 2.1.13 on 2019-10-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0020_auto_20191025_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='date_of_marriage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
