# Generated by Django 2.1.13 on 2019-11-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0020_unapprovedmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unapprovedmember',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
