# Generated by Django 2.1.13 on 2019-10-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0021_auto_20191025_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
