# Generated by Django 2.1.13 on 2019-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0022_auto_20191025_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secondary_user',
            field=models.ManyToManyField(to='church.FileUpload'),
        ),
    ]
