# Generated by Django 2.1.13 on 2019-11-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0022_auto_20191105_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
