# Generated by Django 2.1.13 on 2019-10-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0023_userprofile_secondary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayergroup',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='prayergroup',
            name='user_profile',
            field=models.ManyToManyField(to='church.FileUpload'),
        ),
    ]
