# Generated by Django 2.1.13 on 2019-10-25 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0024_auto_20191025_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_register', models.BooleanField(default=False)),
                ('is_user_add_new_member', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.UserProfile')),
            ],
        ),
    ]
