# Generated by Django 2.1.13 on 2019-11-06 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0024_auto_20191105_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRequestNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.FileUpload')),
            ],
        ),
    ]
