# Generated by Django 2.1.13 on 2019-11-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0024_auto_20191105_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='unapprovedmember',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
