# Generated by Django 2.1.13 on 2019-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0025_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchdetails',
            name='image',
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='image',
            field=models.ManyToManyField(to='church.Images'),
        ),
    ]
