# Generated by Django 2.1.13 on 2019-11-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0025_unapprovedmember_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unapprovedmember',
            name='edit',
        ),
        migrations.AddField(
            model_name='unapprovedmember',
            name='edit_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
