# Generated by Django 2.1.13 on 2019-10-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0026_auto_20191028_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdetails',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='cards/pan_folder/'),
        ),
    ]
