# Generated by Django 2.1.13 on 2019-11-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0027_fileupload_marrige_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='marrige_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
