# Generated by Django 2.1.13 on 2019-10-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0027_auto_20191028_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodels',
            name='user_type',
            field=models.CharField(blank=True, choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('CHURCH', 'CHURCH')], max_length=255, null=True),
        ),
    ]
