# Generated by Django 2.1.13 on 2019-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0028_otpmodels_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_church_user',
            field=models.BooleanField(default=False),
        ),
    ]
