# Generated by Django 2.1.13 on 2019-11-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0028_members_marrige_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayergroup',
            name='primary_user_id',
        ),
        migrations.AddField(
            model_name='prayergroup',
            name='primary_user_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_file_upload_prayergroup', to='church.FileUpload'),
        ),
    ]
