# Generated by Django 2.1.13 on 2019-11-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0030_auto_20191106_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchdetails',
            name='church_name',
            field=models.CharField(default='church', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(default='chruch', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='member_name',
            field=models.CharField(default='member', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.CharField(default='notice', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prayergroup',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unapprovedmember',
            name='member_name',
            field=models.CharField(default='member name', max_length=255),
            preserve_default=False,
        ),
    ]
