# Generated by Django 2.1.13 on 2019-11-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0028_auto_20191106_1228'),
        ('church', '0031_auto_20191106_1706'),
    ]

    operations = [
    ]
