# Generated by Django 2.1.13 on 2019-11-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0035_membertype_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertype',
            name='member_type',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='occupation',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
