# Generated by Django 2.1.13 on 2019-11-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0036_auto_20191106_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticebereavement',
            name='title',
        ),
    ]
