# Generated by Django 2.1.13 on 2019-11-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0037_remove_noticebereavement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayergroup',
            name='sec_member',
            field=models.ManyToManyField(blank=True, null=True, to='church.Members'),
        ),
    ]
