# Generated by Django 2.1.13 on 2019-11-07 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0038_prayergroup_sec_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='noticeread',
            name='msg_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Notification'),
        ),
        migrations.AddField(
            model_name='noticeread',
            name='primary_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.FileUpload'),
        ),
        migrations.AddField(
            model_name='noticeread',
            name='secondary_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Members'),
        ),
    ]
