# Generated by Django 2.1.13 on 2019-11-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191106_1706'),
        ('church', '0039_auto_20191107_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeReadAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeReadPrimary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeReadSecondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='noticeread',
            name='msg_body',
        ),
        migrations.RemoveField(
            model_name='noticeread',
            name='primary_user',
        ),
        migrations.RemoveField(
            model_name='noticeread',
            name='secondary_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_new_register',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_user_add_new_member',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_admin', to='api.AdminProfile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_primary', to='church.FileUpload'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_secondary', to='church.Members'),
        ),
        migrations.DeleteModel(
            name='NoticeRead',
        ),
        migrations.AddField(
            model_name='noticereadsecondary',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Notification'),
        ),
        migrations.AddField(
            model_name='noticereadsecondary',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Members'),
        ),
        migrations.AddField(
            model_name='noticereadprimary',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Notification'),
        ),
        migrations.AddField(
            model_name='noticereadprimary',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.FileUpload'),
        ),
        migrations.AddField(
            model_name='noticereadadmin',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Notification'),
        ),
        migrations.AddField(
            model_name='noticereadadmin',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AdminProfile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_to_admin',
            field=models.ManyToManyField(through='church.NoticeReadAdmin', to='api.AdminProfile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_to_primary',
            field=models.ManyToManyField(through='church.NoticeReadPrimary', to='church.FileUpload'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_to_secondary',
            field=models.ManyToManyField(through='church.NoticeReadSecondary', to='church.Members'),
        ),
    ]
