# Generated by Django 2.1.13 on 2019-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0040_auto_20191107_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewrequestnumber',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='viewrequestnumber',
            name='user',
        ),
        migrations.AddField(
            model_name='viewrequestnumber',
            name='request_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewrequestnumber',
            name='request_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='viewrequestnumber',
            name='request_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewrequestnumber',
            name='usertype_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewrequestnumber',
            name='usertype_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
