# Generated by Django 2.1.13 on 2019-11-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0041_auto_20191107_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unapprovedmember',
            name='in_memory_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
