# Generated by Django 2.1.13 on 2019-11-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0042_auto_20191107_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchVikar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vicar_name', models.CharField(max_length=100)),
                ('vicar_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('vicar_image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.ChurchDetails')),
            ],
        ),
    ]
