# Generated by Django 2.1.13 on 2019-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0043_churchvikar'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_json',
            field=models.BooleanField(default=False),
        ),
    ]
