# Generated by Django 2.1.13 on 2019-11-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0044_notification_is_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchdetails',
            name='vicar_inf',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
