# Generated by Django 2.1.13 on 2019-11-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0045_auto_20191110_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='relation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
