# Generated by Django 2.1.13 on 2019-11-12 10:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0048_auto_20191112_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
