# Generated by Django 2.1.13 on 2019-11-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0049_auto_20191112_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cards/familyimage/'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cards/members/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cards/members/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cards/pan_folder/'),
        ),
        migrations.AlterField(
            model_name='unapprovedmember',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cards/members/'),
        ),
    ]
