# Generated by Django 2.1.13 on 2019-11-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0050_auto_20191113_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='familyimage/'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='members/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='members/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pan_folder/'),
        ),
        migrations.AlterField(
            model_name='unapprovedmember',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='members/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='pan_folder/'),
        ),
    ]
