# Generated by Django 2.1.13 on 2019-11-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0051_auto_20191113_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('phone_type', models.CharField(blank=True, choices=[('IOS', 'IOS'), ('ANDROID', 'ANDROID')], max_length=255, null=True)),
            ],
        ),
    ]
