# Generated by Django 2.1.13 on 2019-11-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0052_phoneversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('church_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churchfolder', to='church.Images')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.ChurchFolder')),
            ],
        ),
    ]
