# Generated by Django 2.1.13 on 2019-11-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0053_churchfolder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='title',
            new_name='category',
        ),
    ]
