# Generated by Django 2.1.13 on 2019-11-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0054_auto_20191119_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticebereavement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
