# Generated by Django 2.1.13 on 2019-11-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0056_images_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayergroup',
            name='family',
            field=models.ManyToManyField(blank=True, null=True, to='church.Family'),
        ),
    ]
