# Generated by Django 2.1.13 on 2019-12-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0057_prayergroup_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='about',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
