# Generated by Django 2.1.13 on 2019-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0058_auto_20191219_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
