# Generated by Django 2.1.13 on 2020-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0061_numberchangeprimary_primarytosecondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberchangeprimary',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='primarytosecondary',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
