# Generated by Django 2.1.13 on 2020-01-23 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0062_auto_20200114_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='unapprovedmember',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='unapprovedmember',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
