# Generated by Django 2.1.13 on 2020-02-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0063_auto_20200123_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unapprovedmember',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
