# Generated by Django 2.1.13 on 2020-03-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0064_auto_20200218_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
