# Generated by Django 2.1.13 on 2020-03-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0065_auto_20200312_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='unapprovedmember',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
