# Generated by Django 2.1.13 on 2020-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0066_unapprovedmember_landline'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_files/'),
        ),
    ]
