# Generated by Django 2.1.13 on 2020-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0067_auto_20200403_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
