# Generated by Django 2.1.13 on 2020-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0068_notice_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
