# Generated by Django 2.1.13 on 2020-05-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0069_family_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticebereavement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
