# Generated by Django 2.1.13 on 2020-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0070_noticebereavement_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticebereavement',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
