# Generated by Django 2.1.13 on 2020-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0071_noticebereavement_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('request_type', models.CharField(blank=True, choices=[('MOBILE', 'MOBILE'), ('FAMILY', 'FAMILY')], max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('CHURCH', 'CHURCH')], max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=20000, null=True)),
            ],
        ),
    ]
