# Generated by Django 2.1.13 on 2020-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0073_auto_20200514_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='description',
            field=models.TextField(default=1, max_length=20000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='request_type',
            field=models.CharField(choices=[('MOBILE', 'MOBILE'), ('FAMILY', 'FAMILY')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
