# Generated by Django 2.1.13 on 2020-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0074_auto_20200514_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchVikars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vicar_name', models.CharField(max_length=100)),
                ('vicar_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('vicar_image', models.FileField(blank=True, null=True, upload_to='pan_folder/')),
                ('start_year', models.CharField(blank=True, max_length=10, null=True)),
                ('end_year', models.CharField(blank=True, max_length=10, null=True)),
                ('vicar_type', models.CharField(blank=True, choices=[('vicar', 'VICAR'), ('asstvicar', 'ASSTVICAR')], max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='request_type',
            field=models.CharField(choices=[('mobile', 'MOBILE'), ('family', 'FAMILY')], max_length=255),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='user_type',
            field=models.CharField(blank=True, choices=[('primary', 'PRIMARY'), ('secondary', 'SECONDARY')], max_length=255, null=True),
        ),
    ]
