# Generated by Django 2.1.13 on 2020-05-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0075_auto_20200525_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChurchVikars',
            new_name='ChurchVicars',
        ),
    ]
