# Generated by Django 2.1.13 on 2020-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0076_auto_20200525_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdetails',
            name='church_place',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='infrastructure',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='organization',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='our_church',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
